# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: |
  Greetings from Munich! ğŸ¥¨
  Thank you very much for participating in our project by opening this issue! â¤
  We will take a look at your issue as soon as possible! ğŸ‘€

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: |
  Greetings from Munich! ğŸ¥¨
  Thank you very much for participating in our project by opening this pull request! â¤
  Please check out our contribution guidelines for further information. â„¹
  We will review your changes as soon as possible! ğŸ‘€

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: |
  It's Munich again! ğŸ¥¨
  Thank you very much for your first successful contribution to our project! â¤
  Munich is proud of you! ğŸ‰
  Until next time! ğŸ‘‹
  
  ![drinking beer](https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExZ2Rrem83bXZ5bmMwcXE1YjkzcnhkdjJtdjN3M2N6cmc0NmtzM25kYiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/3o7TKKdv1vyUpyFLva/giphy.webp)

# It is recommend to include as many gifs and emojis as possible