name: Docker Compose Healthcheck

on:
  # Runs on pull requests
  pull_request:

jobs:
  docker-compose-healthcheck:
    name: Run docker compose healthcheck
    runs-on: ubuntu-latest
    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-dockercompose-healthcheck@12966547963631f8429d42bab860485b413003c2 # v1.0.22
        with:
          skip-exited: true # required for keycloakmigration init container
          compose-file-path: "./stack/"
