name: Release Maven

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Version to use when preparing a release (e.g., 1.2.3)"
        required: true
        default: 0.0.1
      developmentVersion:
        description: "Version to use for new local working copy (e.g., 1.2.4-SNAPSHOT)"
        required: true
        default: 0.0.2-SNAPSHOT
      app-path:
        type: choice
        description: Service-Name
        required: true
        options:
          - refarch-backend
          - refarch-eai

jobs:
  release-maven:
    runs-on: ubuntu-latest
    outputs:
      MVN_ARTIFACT_ID: ${{ steps.maven-release-step.outputs.MVN_ARTIFACT_ID }}
      ARTIFACT_NAME: ${{ steps.maven-release-step.outputs.artifact-name }}
    env:
      TZ: Europe/Berlin # timezone
    steps:
      - id: maven-release-step
        uses: it-at-m/lhm_actions/action-templates/actions/action-maven-release@0f8ed45a5eb72bf1cc2fe1d3dbcbcfb852549c27 # v1.0.17
        with:
          app-path: ${{ github.event.inputs.app-path }}
          releaseVersion: ${{ github.event.inputs.releaseVersion }}
          developmentVersion: ${{ github.event.inputs.developmentVersion }}
          SIGN_KEY_PASS: ${{ secrets.gpg_passphrase }}
          CENTRAL_USERNAME: ${{ secrets.sonatype_username }}
          CENTRAL_PASSWORD: ${{ secrets.sonatype_password }}
          GPG_PRIVATE_KEY: ${{ secrets.gpg_private_key }}

  build-image:
    runs-on: ubuntu-latest
    needs: release-maven
    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-build-image@0f8ed45a5eb72bf1cc2fe1d3dbcbcfb852549c27 # v1.0.17
        with:
          path: ${{ github.event.inputs.app-path }}
          image-name: ${{ github.event.inputs.app-path }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          artifact-name: ${{ needs.release-maven.outputs.ARTIFACT_NAME }}
          registry-username: ${{ github.actor }}
          image-tags: |
            type=semver,pattern={{version}},value=${{ github.event.inputs.releaseVersion }}
            type=raw,value=latest

  create-github-release:
    needs: release-maven
    runs-on: ubuntu-latest
    steps:
      - name: Download a single artifact
        uses: it-at-m/lhm_actions/action-templates/actions/action-create-github-release@0f8ed45a5eb72bf1cc2fe1d3dbcbcfb852549c27 # v1.0.17
        with:
          artifact-name: ${{ needs.release-maven.outputs.ARTIFACT_NAME }}
          tag-name: ${{ inputs.app-path }}-${{ github.event.inputs.releaseVersion }}
          artifact-path: ${{ github.event.inputs.app-path }}/target/*.jar
